### ISSUE TITLE
Add basic ci for text checks

### ISSUE THREAD

**Issue by stp-ip** [okkur/reposeed#18]
* [ ] https://github.com/amperser/proselint <- some basic check for passive voice, offensive terms etc.
* [ ] https://github.com/wooorm/alex

Sidenote: I thought there was some sort of linter to check for the usage of only basic english words between 850-1000 words, but couldn't find it.

**Comment by wooorm** [comment]
If you are doing alex, you may be interested in its `--diff` option if running in Travis.

For the top words, did you mean [cleartext](https://github.com/mortenjust/cleartext-mac)? Something like that could be implemented as a [retext](https://github.com/retextjs/retext) plugin (the base of alex). Let us know in the Gitter chat if you’d like to work on it, and need help!

**Comment by stp-ip** [comment]
Yes similar to cleartext. Will see, if we get some time to add it.
Something along the lines of having the 850, 1k and 2k and maybe 2k + computer word being checked would be interesting. That would make documentation much more readable for non english natives I assume.

Thanks for reaching out.
