### ISSUE TITLE
how it compares to cookiecutter

### ISSUE THREAD

**Issue by errordeveloper** [okkur/reposeed#55]
I'm currios how this tool compares to [cookiecutter](https://github.com/audreyr/cookiecutter)?

I can see that it's written in Go instead of Python, and has significantly different CLI. However, it would be good to know if there is any fundamental difference in philosophy and approach of this tool vs cookiecutter, so that one can tell why they might prefer to use one over the other.

**Comment by stp-ip** [comment]
To give a first rough answer. It is more tailored towards providing a bare repository for projects around licensing, maintainer and contributor docs.

Will have to look more deeply into the various cookiecutter subprojects to compare in detail.

**Comment by errordeveloper** [comment]
So reposeed doesn't cater for stuff like build config templates (e.g.
make/docker/CI), or anything else of similar nature?

**Comment by stp-ip** [comment]
Not at this time.

**Comment by errordeveloper** [comment]
Thanks, good to know!

**Comment by stp-ip** [comment]
Context:
https://github.com/audreyr/cookiecutter
https://github.com/NathanUrwin/cookiecutter-git
https://github.com/lacion/cookiecutter-golang
