### ISSUE TITLE
go get problem

### ISSUE THREAD

**Issue by hhrutter** [okkur/reposeed#61]
Hi!

This is a bug in the read.me.
I am following the install and get this warning:
```
Go-> ~/go/src/github.com: go get -v -u github.com/okkur/reposeed/cmd/reposeed/...
github.com/okkur/reposeed (download)
go: warning: "github.com/okkur/reposeed/cmd/reposeed/..." matched no packages
Go-> ~/go/src/github.com: go version
go version go1.12.5 darwin/amd64
```

This works:
```
go get -u -v github.com/okkur/reposeed/cmd/...
```

**Comment by stp-ip** [comment]
Thanks for reporting. We were reworking some things within reposeed and wanted to move towards a vanity url to pull, which should also fix the README issue. Happy for you to create a PR to fix this specific issue until we get the iteration working.

**Comment by hhrutter** [comment]
That's ok. No need for a PR. I'll check back in a while.

**Comment by stp-ip** [comment]
We now have a vanity url: `go get -u go.okkur.org/reposeed`

Changing the docs right now.

Happy for more feedback and even PRs in the future.
